CREATE TABLE "Company_master" (
  "Company_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Company_Name" varchar(255) NOT NULL,
  "Legal_Name" varchar(255),
  "GSTIN" varchar(15) UNIQUE,
  "PAN" varchar(10) UNIQUE,
  "CIN" varchar(20),
  "Business_Type" varchar(100),
  "Address_Line_1" varchar(500),
  "Address_Line_2" varchar(500),
  "City" varchar(100),
  "State" varchar(100),
  "State_Code" varchar(10),
  "Pincode" varchar(10),
  "Country" varchar(100),
  "Phone" varchar(20),
  "Email" varchar(255),
  "Financial_Year_From" date,
  "Financial_Year_To" date,
  "Currency" varchar(3) DEFAULT 'INR',
  "Books_Beginning_From" date,
  "GST_Applicable" boolean DEFAULT true,
  "Composition_Scheme" boolean DEFAULT false,
  "Created_Date" datetime DEFAULT (now()),
  "Status" varchar(20) DEFAULT 'Active'
);

CREATE TABLE "Ledger_Master" (
  "Ledger_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Company_ID" int,
  "Ledger_Name" varchar(255) NOT NULL,
  "Alias_Name" varchar(255),
  "Parent_Group" varchar(255),
  "Group_Type" varchar(100),
  "Opening_Balance" decimal(15,2) DEFAULT 0,
  "Opening_Balance_Type" varchar(10) DEFAULT 'Dr',
  "GST_Applicable" boolean DEFAULT false,
  "GST_Tax_Type" varchar(50),
  "GST_Rate" decimal(5,2) DEFAULT 0,
  "HSN_SAC" varchar(20),
  "Is_Bill_Wise" boolean DEFAULT false,
  "Credit_Limit" decimal(15,2) DEFAULT 0,
  "Maintain_Balances_Bill_Wise" boolean DEFAULT false,
  "Status" varchar(20) DEFAULT 'Active'
);

CREATE TABLE "Party_Master" (
  "Party_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Company_ID" int,
  "Ledger_ID" int,
  "Party_Type" varchar(50) NOT NULL,
  "Party_Name" varchar(255) NOT NULL,
  "GSTIN" varchar(15),
  "PAN" varchar(10),
  "Contact_Person" varchar(255),
  "Phone" varchar(20),
  "Email" varchar(255),
  "Billing_Address" text,
  "Shipping_Address" text,
  "State" varchar(100),
  "State_Code" varchar(10),
  "Credit_Period" int DEFAULT 30,
  "Credit_Limit" decimal(15,2) DEFAULT 0,
  "Opening_Balance" decimal(15,2) DEFAULT 0,
  "Balance_Type" varchar(10) DEFAULT 'Dr',
  "TDS_Applicable" boolean DEFAULT false,
  "Status" varchar(20) DEFAULT 'Active'
);

CREATE TABLE "Item_Master" (
  "Item_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Company_ID" int,
  "Item_Name" varchar(255) NOT NULL,
  "Alias_Name" varchar(255),
  "Category" varchar(100),
  "Unit" varchar(20),
  "HSN_Code" varchar(20),
  "GST_Rate" decimal(5,2) DEFAULT 0,
  "Purchase_Rate" decimal(12,2) DEFAULT 0,
  "Sales_Rate" decimal(12,2) DEFAULT 0,
  "MRP" decimal(12,2) DEFAULT 0,
  "Opening_Stock" decimal(12,3) DEFAULT 0,
  "Opening_Stock_Value" decimal(15,2) DEFAULT 0,
  "Reorder_Level" decimal(12,3) DEFAULT 0,
  "Batch_Applicable" boolean DEFAULT false,
  "Expiry_Date" date,
  "Status" varchar(20) DEFAULT 'Active'
);

CREATE TABLE "Employee_Master" (
  "Employee_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Company_ID" int,
  "Employee_Name" varchar(255) NOT NULL,
  "Department" varchar(100),
  "Designation" varchar(100),
  "Date_of_Joining" date NOT NULL,
  "Mobile" varchar(15),
  "Email" varchar(255),
  "Salary" decimal(12,2) DEFAULT 0,
  "Attendance_Applicable" boolean DEFAULT true,
  "PF_Applicable" boolean DEFAULT false,
  "ESI_Applicable" boolean DEFAULT false,
  "Status" varchar(20) DEFAULT 'Active'
);

CREATE TABLE "Sales_Voucher" (
  "Sales_Voucher_No" varchar(50) PRIMARY KEY,
  "Company_ID" int,
  "Voucher_Date" date NOT NULL,
  "Party_ID" int,
  "Invoice_No" varchar(50),
  "Invoice_Date" date,
  "GST_Type" varchar(50),
  "Total_Tax" decimal(15,2),
  "Round_Off" decimal(10,2) DEFAULT 0,
  "Total_Invoice_Value" decimal(15,2) NOT NULL,
  "Payment_Status" varchar(50) DEFAULT 'Pending',
  "Created_By" int
);

CREATE TABLE "Purchase_Voucher" (
  "Purchase_Voucher_No" varchar(50) PRIMARY KEY,
  "Company_ID" int,
  "Voucher_Date" date NOT NULL,
  "Vendor_ID" int,
  "Invoice_No" varchar(50),
  "Invoice_Date" date,
  "Total_Tax" decimal(15,2),
  "Total_Amount" decimal(15,2) NOT NULL,
  "Reverse_Charge" boolean DEFAULT false,
  "Input_Tax_Credit" decimal(15,2) DEFAULT 0,
  "Payment_Status" varchar(50) DEFAULT 'Pending'
);

CREATE TABLE "Voucher_Line_Items" (
  "Line_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Company_ID" int,
  "Voucher_Type" varchar(20) NOT NULL,
  "Sales_Voucher_No" varchar(50),
  "Purchase_Voucher_No" varchar(50),
  "Item_ID" int,
  "Quantity" decimal(12,3) NOT NULL,
  "Rate" decimal(12,2) NOT NULL,
  "Discount" decimal(6,2) DEFAULT 0,
  "Taxable_Value" decimal(15,2) NOT NULL,
  "CGST_Rate" decimal(5,2),
  "CGST_Amount" decimal(12,2),
  "SGST_Rate" decimal(5,2),
  "SGST_Amount" decimal(12,2),
  "IGST_Rate" decimal(5,2),
  "IGST_Amount" decimal(12,2),
  "Line_Total" decimal(15,2)
);

CREATE TABLE "Payment_Receipt" (
  "Transaction_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Company_ID" int,
  "Transaction_Type" varchar(50) NOT NULL,
  "Voucher_No" varchar(50),
  "Voucher_Date" date,
  "Party_ID" int,
  "Payment_Mode" varchar(50) NOT NULL,
  "Bank_Name" varchar(255),
  "Reference_No" varchar(100),
  "Amount" decimal(15,2) NOT NULL,
  "Narration" text,
  "Created_By" int
);

CREATE TABLE "Expense_Voucher" (
  "Expense_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Company_ID" int,
  "Expense_Date" date NOT NULL,
  "Expense_Category" varchar(100),
  "Ledger_ID" int,
  "Amount" decimal(15,2) NOT NULL,
  "GST_Applicable" boolean DEFAULT false,
  "GST_Amount" decimal(12,2) DEFAULT 0,
  "Payment_Mode" varchar(50),
  "Paid_To" varchar(255),
  "Reference_No" varchar(100),
  "Remarks" text
);

CREATE TABLE "Employee_Attendance" (
  "Attendance_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Employee_ID" int,
  "Date" date NOT NULL,
  "Punch_In_Time" time,
  "Punch_Out_Time" time,
  "Working_Hours" decimal(5,2),
  "Overtime_Hours" decimal(5,2) DEFAULT 0,
  "Attendance_Status" varchar(50) DEFAULT 'Present'
);

CREATE TABLE "GST_Report_Data" (
  "GSTIN" varchar(15),
  "Period" varchar(10),
  "Return_Type" varchar(50),
  "Company_ID" int,
  "Taxable_Value" decimal(15,2),
  "CGST" decimal(15,2),
  "SGST" decimal(15,2),
  "IGST" decimal(15,2),
  "Total_Tax_Liability" decimal(15,2),
  "ITC_Claimed" decimal(15,2),
  "Net_Tax_Payable" decimal(15,2),
  PRIMARY KEY ("GSTIN", "Period", "Return_Type")
);

CREATE TABLE "Documents" (
  "Document_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Company_ID" int,
  "Document_Type" varchar(100),
  "Linked_Table" varchar(50),
  "Linked_ID" varchar(50) NOT NULL,
  "Uploaded_By" int,
  "Upload_Date" datetime DEFAULT (now()),
  "File_Name" varchar(255) NOT NULL,
  "File_URL" varchar(500)
);

CREATE TABLE "Digital_Sign" (
  "Sign_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Document_ID" int,
  "Signed_By" varchar(255) NOT NULL,
  "Sign_Date" datetime DEFAULT (now()),
  "Sign_Status" varchar(50) DEFAULT 'Pending',
  "IP_Address" varchar(45)
);

CREATE TABLE "CRM_Leads" (
  "Lead_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Company_ID" int,
  "Lead_Source" varchar(100),
  "Customer_Name" varchar(255) NOT NULL,
  "Mobile" varchar(15),
  "Email" varchar(255),
  "Assigned_To" int,
  "Lead_Status" varchar(50) DEFAULT 'New',
  "Follow_Up_Date" date,
  "Remarks" text
);

CREATE TABLE "Marketing_Campaign" (
  "Campaign_ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Company_ID" int,
  "Campaign_Type" varchar(50),
  "Campaign_Name" varchar(255) NOT NULL,
  "Target_Audience" text,
  "Message_Content" text,
  "Scheduled_Date" datetime,
  "Sent_Count" int DEFAULT 0,
  "Delivered_Count" int DEFAULT 0,
  "Response_Count" int DEFAULT 0
);

ALTER TABLE "Ledger_Master" ADD FOREIGN KEY ("Company_ID") REFERENCES "Company_master" ("Company_ID");

ALTER TABLE "Party_Master" ADD FOREIGN KEY ("Company_ID") REFERENCES "Company_master" ("Company_ID");

ALTER TABLE "Party_Master" ADD FOREIGN KEY ("Ledger_ID") REFERENCES "Ledger_Master" ("Ledger_ID");

ALTER TABLE "Item_Master" ADD FOREIGN KEY ("Company_ID") REFERENCES "Company_master" ("Company_ID");

ALTER TABLE "Employee_Master" ADD FOREIGN KEY ("Company_ID") REFERENCES "Company_master" ("Company_ID");

ALTER TABLE "Sales_Voucher" ADD FOREIGN KEY ("Company_ID") REFERENCES "Company_master" ("Company_ID");

ALTER TABLE "Sales_Voucher" ADD FOREIGN KEY ("Party_ID") REFERENCES "Party_Master" ("Party_ID");

ALTER TABLE "Sales_Voucher" ADD FOREIGN KEY ("Created_By") REFERENCES "Employee_Master" ("Employee_ID");

ALTER TABLE "Purchase_Voucher" ADD FOREIGN KEY ("Company_ID") REFERENCES "Company_master" ("Company_ID");

ALTER TABLE "Purchase_Voucher" ADD FOREIGN KEY ("Vendor_ID") REFERENCES "Party_Master" ("Party_ID");

ALTER TABLE "Voucher_Line_Items" ADD FOREIGN KEY ("Company_ID") REFERENCES "Company_master" ("Company_ID");

ALTER TABLE "Voucher_Line_Items" ADD FOREIGN KEY ("Item_ID") REFERENCES "Item_Master" ("Item_ID");

ALTER TABLE "Payment_Receipt" ADD FOREIGN KEY ("Company_ID") REFERENCES "Company_master" ("Company_ID");

ALTER TABLE "Payment_Receipt" ADD FOREIGN KEY ("Party_ID") REFERENCES "Party_Master" ("Party_ID");

ALTER TABLE "Payment_Receipt" ADD FOREIGN KEY ("Created_By") REFERENCES "Employee_Master" ("Employee_ID");

ALTER TABLE "Expense_Voucher" ADD FOREIGN KEY ("Company_ID") REFERENCES "Company_master" ("Company_ID");

ALTER TABLE "Expense_Voucher" ADD FOREIGN KEY ("Ledger_ID") REFERENCES "Ledger_Master" ("Ledger_ID");

ALTER TABLE "Employee_Attendance" ADD FOREIGN KEY ("Employee_ID") REFERENCES "Employee_Master" ("Employee_ID");

ALTER TABLE "GST_Report_Data" ADD FOREIGN KEY ("Company_ID") REFERENCES "Company_master" ("Company_ID");

ALTER TABLE "Documents" ADD FOREIGN KEY ("Company_ID") REFERENCES "Company_master" ("Company_ID");

ALTER TABLE "Documents" ADD FOREIGN KEY ("Uploaded_By") REFERENCES "Employee_Master" ("Employee_ID");

ALTER TABLE "Digital_Sign" ADD FOREIGN KEY ("Document_ID") REFERENCES "Documents" ("Document_ID");

ALTER TABLE "CRM_Leads" ADD FOREIGN KEY ("Company_ID") REFERENCES "Company_master" ("Company_ID");

ALTER TABLE "CRM_Leads" ADD FOREIGN KEY ("Assigned_To") REFERENCES "Employee_Master" ("Employee_ID");

ALTER TABLE "Marketing_Campaign" ADD FOREIGN KEY ("Company_ID") REFERENCES "Company_master" ("Company_ID");
